server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false
    username: root
    password: UsefulOtter

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
